### ISSUE TITLE
Small path update in instructions

### ISSUE THREAD

**Issue by mgalexander** [csantanapr/mfp-ionic-templates#1]
Following along I hit a small bump..

```
mfproject malexander$ cp -r mfp-ionic-templates/tabs/common coolApp/
cp: directory coolApp does not exist
```

instead it looks like the path is just the parent since I have to be in this location per the prior instruction
    `mfproject malexander$ cp -r ../common apps/coolApp/`

**Comment by csantanapr** [comment]
Thanks for reporting the issue @mgalexander
