### ISSUE TITLE
using bower, gulp, etc

### ISSUE THREAD

**Issue by drkhannah** [csantanapr/mfp-ionic-templates#2]
If i follow the instructions to use your template, there is no package.json, and not bower.json in my common folder

I want to use Gulp, Karma, Angular Modules (like ngCorodva) etc.

how do I go about this

should I just do an npm init and bower init in the common folder after following your readme instructions?

should I copy the bower.json of your template to my common folder?

am i going about this the wrong way?

**Comment by csantanapr** [comment]
you can put package.json and bower.json outside common folder, same level of common folder. treat common folder like the www cordova/ionic folder, everything inside the common folder will end up inside your app/device
